apiVersion: v1
data:
  config.yml: |
    global:
      config_version: 3
    input:
      type: file
      path: /data/spool/uucp/Log
      readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
    # imports:
    # - type: grok_patterns
    #   dir: /patterns
    grok_patterns:
    - 'YEAR (?>\d\d){1,2}'
    - 'HOUR (?:2[0123]|[01]?[0-9])'
    - 'MINUTE (?:[0-5][0-9])'
    - 'SECOND (?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)'
    - 'TIME (?!<[0-9])%{HOUR}:%{MINUTE}(?::%{SECOND})(?![0-9])'
    - 'UUCP_MESSAGE [a-zA-Z ]*'
    - 'UUCP_USER [0-9]{13}'
    - 'UUCP_DATE %{YEAR:uucp_year}-%{MONTHNUM:uucp_month}-%{MONTHDAY:uucp_day} %{TIME:uucp_time}'
    metrics:
    - type: counter
      name: gnuu_uucp_logins
      help: Total number of UUCP Logins
      match: 'uucico - - (%{UUCP_DATE}) Incoming call (login %{UUCP_USER} port stdin)'
      labels:
        logfile: '{{base .logfile}}'
    server:
      protocol: http
      port: 9144
kind: ConfigMap
metadata:
  labels:
    app: groklog
  name: groklog
---
apiVersion: v1
data:
  uucp: |
    UUCP_USER [0-9]{13}
    UUCP_DATE %{YEAR:uucp_year}-%{MONTHNUM:uucp_month}-%{MONTHDAY:uucp_day} %{TIME:uucp_time}
kind: ConfigMap
metadata:
  labels:
    app: groklog
  name: grokpatterns
