apiVersion: apps/v1
kind: Deployment
metadata:
  name: groklog
  labels:
    app: groklog
spec:
  selector:
    matchLabels:
      app: groklog
  template:
    metadata:
      labels:
        app: groklog
    spec:
      containers:
        - image: 'gnuu/grok_exporter:latest'
          imagePullPolicy: Always
          name: grok-exporter
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            privileged: false
            allowPrivilegeEscalation: true
            runAsUser: 1000
          ports:
            - name: groklog
              protocol: TCP
              containerPort: 9144
          env:
            - name: GROKCONF
              value: /app/example/config.yml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
